/* Landing pública: mantém a apresentação isolada da aplicação em /app/. */
(function () {
  const appUrl = (hash) => '/app/' + (hash || '');
  const publicMatch = location.pathname.match(/^\/b\/([a-z0-9-]+)\/?$/i);
  const directSlugMatch = location.pathname.match(/^\/([a-z0-9-]+)\/?$/i);
  const legacyHash = location.hash;

  function renderPublicSlug(slug) {
    document.title = 'Groomin — Agendamento online';
    if (typeof renderPublic === 'function') renderPublic({ route: 'public', slug: decodeURIComponent(slug || '') });
    else $('#root').innerHTML = `<div class="container" style="padding:80px 0;text-align:center"><h2>Carregando...</h2></div>`;
  }

  // Link público compartilhável: /b/nome-da-barbearia.
  if (publicMatch) {
    renderPublicSlug(publicMatch[1]);
    return;
  }

  // New public booking URL generated by onboarding: groomin.com.br/slug.
  if (directSlugMatch && !['app','auth','assets','js'].includes(directSlugMatch[1].toLowerCase())) {
    renderPublicSlug(directSlugMatch[1]);
    return;
  }

  // URLs compartilhadas da versão anterior continuam válidas.
  if (legacyHash && legacyHash !== '#/' && legacyHash !== '#') {
    location.replace(appUrl(legacyHash));
    return;
  }

  const originalGo = Router.go.bind(Router);
  Router.go = function (path) {
    if (path === '#/' || path === '/') return originalGo('#/');
    location.href = appUrl(path);
  };

  // Os CTAs da landing: se já logado vai pro dashboard, senão abre signup.
  window.openOnboarding = window.openTrialSignup = function (planId) {
    try {
      const su=JSON.parse(sessionStorage.getItem('groomin_user'));
      if(su&&su.barbershopId){location.href=appUrl('#/dashboard/assinatura');return;}
      if(su){location.href=appUrl('#/signup');return;}
    } catch(e){}
    if(planId)sessionStorage.setItem('groomin_signup_plan',planId);
    location.href=appUrl('#/signup');
  };
  window.openDemo = function () {
    location.href = appUrl('#/login');
  };

  document.title = 'Groomin — Página profissional de agendamentos';
  renderLanding();
  if(window.__FB_ENABLED&&window.fbLoadPlatformSettings){
    fbLoadPlatformSettings().then(()=>{const w=document.getElementById('pricingWrap');if(w)w.innerHTML=pricingInner();}).catch(()=>{});
  }
})();
