/* Landing pública: mantém a apresentação isolada da aplicação em /app/. */
(function () {
  const appUrl = (hash) => '/app/' + (hash || '');
  const publicMatch = location.pathname.match(/^\/b\/([a-z0-9-]+)\/?$/i);
  const directSlugMatch = location.pathname.match(/^\/([a-z0-9-]+)\/?$/i);
  const legacyHash = location.hash;

  // Link público compartilhável: /b/nome-da-barbearia.
  if (publicMatch) {
    location.replace(appUrl('#/b/' + encodeURIComponent(publicMatch[1])));
    return;
  }

  // New public booking URL generated by onboarding: groomin.com.br/slug.
  if (directSlugMatch && !['app','auth','assets','js'].includes(directSlugMatch[1].toLowerCase())) {
    location.replace(appUrl('#/b/' + encodeURIComponent(directSlugMatch[1])));
    return;
  }

  // URLs compartilhadas da versão anterior continuam válidas.
  if (legacyHash && legacyHash !== '#/' && legacyHash !== '#') {
    location.replace(appUrl(legacyHash));
    return;
  }

  const originalGo = Router.go.bind(Router);
  Router.go = function (path) {
    if (path === '#/' || path === '/') return originalGo('#/');
    location.href = appUrl(path);
  };

  // Os CTAs da landing: se já logado vai pro dashboard, senão abre signup.
  window.openOnboarding = window.openTrialSignup = function (planId) {
    try {
      const su=JSON.parse(sessionStorage.getItem('groomin_user'));
      if(su&&su.barbershopId){location.href=appUrl('#/dashboard/assinatura');return;}
      if(su){location.href=appUrl('#/signup');return;}
    } catch(e){}
    location.href=appUrl('#/signup'+(planId?'?plan='+planId:''));
  };
  window.openDemo = function () {
    location.href = appUrl('#/login');
  };

  document.title = 'Groomin — Plataforma Completa de Gestão para Barbearias';
  renderLanding();
})();
